spring.application.name=library-management-backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-raspy-pond-ayz5seqw-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_eCaTwlPHF24X
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

jwt.secret=${JWT_SECRET:+0v7ldArgxW1JWgj9ftszSly474dzzfcUPxJV2V41Zg=}
jwt.expiration=${JWT_EXPIRATION:86400000}

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS: http://localhost:5173}
